### ISSUE TITLE
Goroutine leak detected

### ISSUE THREAD

**Issue by nghiant3223** [haunt98/go-test-color#1]
I added a test file `main_test.go` with the following content:

```go
package main

import "testing"

func TestX(t *testing.T) {
	if 1 != 2 {
		t.Fail()
	}
}
```

Then I ran this test file and got the following output (which is fine):

```
--- FAIL: TestX (0.00s)
FAIL
exit status 1
FAIL    github.com/haunt98/go-test-color        0.333s
2022/07/24 14:28:42 Failed to wait: exit status 1
```

When I added a `time.Sleep(2*time.Second)` at line [64](https://github.com/haunt98/go-test-color/blob/main/main.go#L64) to mimic a very costly operation and ran the test again, I got the following result:

```
--- FAIL: TestX (0.00s)
FAIL
2022/07/24 14:31:32 Failed to wait: exit status 1
```

The above result doesn't contain execution time of this test package (`FAIL    github.com/haunt98/go-test-color        0.333s`). Thus, goroutine leak is happening with your code.

**Comment by haunt98** [comment]
@nghiant3223 Please try again to make sure new fix is worked for you

https://user-images.githubusercontent.com/5424272/184478655-d4ff408a-2fd8-49de-95ec-ca0cdd024b5e.mov
